### ISSUE TITLE
[Bug] DeepSeek-R1-Q8_0使用fp8推理时报错

### ISSUE THREAD

**Issue by xufengnian** [kvcache-ai/ktransformers#1007]
### 检查清单

- [x] 1. 我已经搜索过相关问题，但未能获得预期的帮助
- [x] 2. 该问题在最新版本中尚未修复
- [x] 3. 请注意，如果您提交的BUG相关 issue 缺少对应环境信息和最小可复现示例，我们将难以复现和定位问题，降低获得反馈的可能性
- [x] 4. 如果您提出的不是bug而是问题，请在讨论区发起讨论 https://github.com/kvcache-ai/ktransformers/discussions。否则该 issue 将被关闭
- [x] 5. 为方便社区交流，我将使用中文/英文或附上中文/英文翻译（如使用其他语言）。未附带翻译的非中文/英语内容可能会被关闭

### 问题描述

参考教程https://kvcache-ai.github.io/ktransformers/en/fp8_kernel.html

我在4090D上分别下载了贵方提供的DS-R1-q4km-fp8权重，推理过程正常

也使用了合并脚本，merge_tensors/merge_safetensor_gguf.py自行合并了DS-V3-0324-q4km和DS-V3-0324官方safetensors权重，并运行，推理过程正常

但是当我使用合并脚本，合并DS-R1-Q8_0权重和DS-R1官方权重时，合并没有问题，得到safetensors，但是推理过程报错

`2025-04-01 14:37:06,843 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
2025-04-01 14:37:07,242 INFO /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/main.py[29]: Creating SQL tables
2025-04-01 14:37:07,244 INFO /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/api/openai/assistants/assistants.py[75]: Creating default assistant
2025-04-01 14:37:47,689 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/context_manager.py[21]: Creating Context Manager
INFO:     Started server process [24115]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2025-04-01 14:38:07,492 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/transformers.py[197]: get input ids of shape torch.Size([1, 5])
2025-04-01 14:38:07,496 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py[133]: input_ids: torch.Size([1, 7])
2025-04-01 14:38:07,497 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py[159]: same prefix len: 0
2025-04-01 14:38:07,498 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py[168]: input_ids: torch.Size([1, 7])
2025-04-01 14:38:07,498 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py[170]: generate_ids: torch.Size([1, 0])
2025-04-01 14:38:07,498 DEBUG /home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py[181]: cache position: 0 to 7
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/responses.py", line 268, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/responses.py", line 264, in wrap
    await func()
  File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/responses.py", line 233, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 531, in receive
    await self.message_event.wait()
  File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7e7117fbba50

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
  |     raise exc
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/responses.py", line 261, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 767, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/responses.py", line 264, in wrap
    |     await func()
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/starlette/responses.py", line 245, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/schemas/assistants/streaming.py", line 80, in check_client_link
    |     async for event in async_events:
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/schemas/assistants/streaming.py", line 93, in to_stream_reply
    |     async for event in async_events:
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/schemas/assistants/streaming.py", line 87, in add_done
    |     async for event in async_events:
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/schemas/assistants/streaming.py", line 107, in filter_chat_chunk
    |     async for event in async_events:
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/api/openai/endpoints/chat.py", line 34, in inner
    |     async for token in interface.inference(input_message,id):
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py", line 217, in inference
    |     async for v in super().inference(local_messages, thread_id):
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/transformers.py", line 389, in inference
    |     for t in self.prefill(input_ids, self.check_is_new(thread_id)):
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    |     response = gen.send(None)
    |                ^^^^^^^^^^^^^^
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/ktransformers.py", line 207, in prefill
    |     next_token = self.logits_to_token(logits[0, -1, :])
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/getui/miniconda3/envs/ktransformers-env/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/transformers.py", line 232, in logits_to_token
    |     last = torch.multinomial(probs, num_samples=1)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | RuntimeError: CUDA error: device-side assert triggered
    | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    | For debugging consider passing CUDA_LAUNCH_BLOCKING=1
    | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
    | 
    +------------------------------------
/pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.`

### 复现步骤

ktransformers --model_path /home/USERNAME/model/DeepSeek-R1 --gguf_path /mnt/modelfp8/DeepSeek-R1-q8-fp8 --cpu_infer 40 --max_new_tokens 8192 --cache_lens 32768 --total_context 32768  --temperature 0.6 --port 20000 --host 0.0.0.0 --force_think --api_key sk-xxxx --optimize_config_path /home/USERNAME/tools/ktransformers/ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-fp8-linear-ggml-experts.yaml

### 环境信息

配置信息
内存：768G DDR4
GPU:  4090D
CPU:  INTEL Sliver 4310 *2
未使用NUMA

**Comment by oubeichen** [comment]
如果直接用 DeepSeek-V3-Chat.yaml 运行 Q8 的 gguf 能正常使用吗？

**Comment by xufengnian** [comment]
@oubeichen unsloth的Q8_0权重跑得没问题，但是是GPU int4 + CPU int8，我现在希望GPU FP8 +CPU int8，所以需要自己做合并权重，但是合并权重加载OK，推理报错（V3 0324我也做了Q4KM的合并权重，这个就可以正常推理），所以很疑惑

**Comment by Azure-Tang** [comment]
> 如果直接用 DeepSeek-V3-Chat.yaml 运行 Q8 的 gguf 能正常使用吗？
> 
> 我也想尽可能使用更高的量化，但 原版 FP8 似乎无法使用 kt 运行，而 FP16 应该要用掉 1.3T 以上内存，没这个条件。

原版的Q8应该可以直接使用。不过在gpu部分marlin默认是4bit，也可以通过改yaml来实现8bit marlin：

```yaml
- match:
    name: "^lm_head$"  
    class: torch.nn.Linear 
  replace:
    class: ktransformers.operators.linear.KTransformersLinear  # optimized Kernel on quantized data types
    kwargs:
      generate_device: "cuda"
      prefill_device: "cuda"
      num_bits: 8 # <- add this
      generate_op: "KLinearMarlin"
      prefill_op: "KLinearTorch"
```

**Comment by Azure-Tang** [comment]
> [@oubeichen](https://github.com/oubeichen) unsloth的Q8_0权重跑得没问题，但是是GPU int4 + CPU int8，我现在希望GPU FP8 +CPU int8，所以需要自己做合并权重，但是合并权重加载OK，推理报错（V3 0324我也做了Q4KM的合并权重，这个就可以正常推理），所以很疑惑

确实是有点奇怪，可能是没用对yaml？我看这个报错也看不出来是哪里挂掉了，我建议往代码里多加一些torch.cuda.synchronize()，看一下具体是挂在哪里了

**Comment by xufengnian** [comment]
> > [@oubeichen](https://github.com/oubeichen) unsloth的Q8_0权重跑得没问题，但是是GPU int4 + CPU int8，我现在希望GPU FP8 +CPU int8，所以需要自己做合并权重，但是合并权重加载OK，推理报错（V3 0324我也做了Q4KM的合并权重，这个就可以正常推理），所以很疑惑
> 
> 确实是有点奇怪，可能是没用对yaml？我看这个报错也看不出来是哪里挂掉了，我建议往代码里多加一些torch.cuda.synchronize()，看一下具体是挂在哪里了

yaml文件这块用的是[DeepSeek-V3-Chat-fp8-linear-ggml-experts-serve.yaml](https://github.com/kvcache-ai/ktransformers/blob/main/ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-fp8-linear-ggml-experts-serve.yaml)，没有做修改，权重这块是我这边使用咱们提供的脚本合并的FP8原始权重和Unsloth的Q8_0


同时我测试下来Q4_K_M_FP8的表现反而不如Q4_K_M，我理解可能有一下原因：
- 优化程度不同：Q4和Q8版本是unsloth团队经过了更精细的校准和优化，针对关键层和权重进行了特殊处理
- 混合精度问题：Q4-FP8模型在GPU(FP8)和CPU(INT4)之间切换时可能产生额外误差
- 数值表示方式差异： INT4虽然只有16个值，但分布均匀；FP8虽然值更多，但分布不均(靠近0处密集，远离0处稀疏)；对于某些计算任务，均匀分布的INT4可能恰好保留了关键区间的精度

**Comment by xufengnian** [comment]
这个结论是我用一些问题测试的结果，如有需要我可以发给你看下
合并之前的Q8_0可以跑，就速度慢点，大概3.5T/s

**Comment by xufengnian** [comment]
@Azure-Tang 辛苦老哥，然后benchmark有没有推荐，我也可以跑一下

**Comment by Azure-Tang** [comment]
> [@Azure-Tang](https://github.com/Azure-Tang) 辛苦老哥，然后benchmark有没有推荐，我也可以跑一下

fyi：https://kvcache-ai.github.io/ktransformers/en/benchmark.html
