### ISSUE TITLE
[Bug] balance_serve - CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by createthis** [kvcache-ai/ktransformers#1062]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/kvcache-ai/ktransformers/discussions. Otherwise, it will be closed.
- [x] 5. To help the community, I will use Chinese/English or attach an Chinese/English translation if using another language. Non-Chinese/English content without translation may be closed.

### Describe the bug

```
2025-04-07 03:47:27,391 WARNING /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/ba
ckend/interfaces/balance_serve.py[320]: change system to user
2025-04-07 03:47:27,391 WARNING /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/ba
ckend/interfaces/balance_serve.py[326]: merge two adjacent user messages
2025-04-07 03:47:27,391 WARNING /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/ba
ckend/interfaces/balance_serve.py[326]: merge two adjacent user messages
2025-04-07 03:47:27,431 DEBUG /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/back
end/interfaces/balance_serve.py[335]: get input ids of shape torch.Size([1, 6483])
add query id: 1, batch.query_lengths: 6483, batch_query_tokens: torch.Size([7507]), batch.block_indexes: tensor([ 0,  1,  2,  3,  
4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=torch.int32)
2025-04-07 03:47:28,978 - INFO - flashinfer.jit: Loading JIT ops: sampling
2025-04-07 03:47:28,987 - INFO - flashinfer.jit: Finished loading JIT ops: sampling
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/balance
_serve.py", line 249, in run_engine
    engine.loop()
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/balance
_serve.py", line 227, in loop
    generated_tokens, probs = self.sampling( self.model_runner.output)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/backend/interfaces/balance
_serve.py", line 191, in sampling
    generated_tokens, probs=self.sampler(logit, sample_options)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wra
pped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _cal
l_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/balance_serve/inference/sampling/sampler.py", line 97, in forward
    temperature_0_idx = torch.where(sampling_config.temperatures == 0)[0]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7a3815410788 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x7a38153b9ea8 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3c2 (0x7a38154e93d2 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x29abd (0x7a38154bcabd in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x29da1 (0x7a38154bcda1 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x711b92 (0x7a380c511b92 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x4fc6d8 (0x7a380c2fc6d8 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x603a5 (0x7a38153f13a5 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7a38153eafe9 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x7ba618 (0x7a380c5ba618 in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #10: THPVariable_subclass_dealloc(_object*) + 0x2ad (0x7a380c5ba92d in /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #11: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x4f5eb7]
frame #12: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x5031bf]
frame #13: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x55f246]
frame #14: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x50302a]
frame #15: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x50302a]
frame #16: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x55f246]
frame #17: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x55ef87]
frame #18: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x55f040]
frame #19: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x541355]
frame #20: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x53fd88]
frame #21: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x53fdc4]
frame #22: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x53fdc4]
frame #23: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x54e833]
frame #24: _PyEval_EvalFrameDefault + 0x46f9 (0x515ac9 in /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python)
frame #25: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x5cc3aa]
frame #26: PyEval_EvalCode + 0x9f (0x5cba7f in /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python)
frame #27: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x5ecba7]
frame #28: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x5e8740]
frame #29: PyRun_StringFlags + 0x5f (0x5db24f in /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python)
frame #30: PyRun_SimpleStringFlags + 0x3b (0x5daffb in /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python)
frame #31: Py_RunMain + 0x388 (0x5f7498 in /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python)
frame #32: Py_BytesMain + 0x39 (0x5bc149 in /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python)
frame #33: <unknown function> + 0x2a1ca (0x7a3817a2a1ca in /lib/x86_64-linux-gnu/libc.so.6)
frame #34: __libc_start_main + 0x8b (0x7a3817a2a28b in /lib/x86_64-linux-gnu/libc.so.6)
frame #35: /home/jesse/anaconda3/envs/ktransformers_mc26/bin/python() [0x5bbf93]
```

### Reproduction

1. Start a session with Open Hands AI using the OpenAI API.
2. Ask Open Hands AI to do something. It immediately breaks ktransformers balance_serve.

### Environment

ktransformers v0.2.4post1

Cuda 12.6
Ubuntu 24.04.02 LTS
Dual EPYC 9355 CPUs
768gb RAM
24gb 3090

```bash
python ktransformers/server/main.py \
  --port 11434 \
  --model_path /data/DeepSeek-V3 \
  --model_name "DeepSeek-V3-0324:671b-q4_k_m" \
  --gguf_path /data/DeepSeek-V3-0324/q4_files/Q4_K_M \
  --optimize_config_path ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-serve.yaml \
  --max_new_tokens 1024 \
  --cpu_infer 30 \
  --cache_lens 131072 \
  --chunk_size 256 \
  --max_batch_size 4 \
  --temperature 0.3 \
  --backend_type balance_serve
```

**Comment by createthis** [comment]
I *think* it's failing at the same point where the normal `ktransformers` backend would output the following:
```
2025-04-07 04:00:59,451 WARNING /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/ba
ckend/interfaces/transformers.py[167]: change system to user
2025-04-07 04:00:59,451 WARNING /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/ba
ckend/interfaces/transformers.py[173]: merge two adjacent user messages
2025-04-07 04:00:59,451 WARNING /home/jesse/anaconda3/envs/ktransformers_mc26/lib/python3.11/site-packages/ktransformers/server/ba
ckend/interfaces/transformers.py[173]: merge two adjacent user messages
```

**Comment by qiyuxinlin** [comment]
Hi @createthis, this error is probably caused by temperature = 0. Please try again with the latest code.

**Comment by createthis** [comment]
@qiyuxinlin I checked out `main`, recompiled, and re-ran with `balance_serve`. Open Hands AI no longer crashes! That fixed it.

**Comment by qiyuxinlin** [comment]
@createthis Thank you for your feedback and assistance! I'm glad to hear the issue has been resolved. If you encounter any further issues, feel free to let me know. Thanks again!

**Comment by abxis** [comment]
i use command：python ktransformers/server/main.py --port 10002 --host 0.0.0.0 --model_path /root/model/DeepSeek-R1-0528 --gguf_path /root/model/DeepSeek-R1-0528-GGUF_UD-IQ2_M/UD-IQ2_M  --optimize_config_path ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-serve.yaml   --max_new_tokens 1024 --cache_lens 32768 --chunk_size 256 --max_batch_size 4 --backend_type balance_serve --force_think  ，the same problem occurs again
