### ISSUE TITLE
部署DeepSeek-R1-Q4_K_M推理时出错

### ISSUE THREAD

**Issue by tunantu** [kvcache-ai/ktransformers#876]
按照官方文档部署了DeepSeek-R1-Q4_K_M，但是在推理的时候，生成第一个token的时候报错：

/pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wangks/ktransformers/ktransformers/local_chat.py", line 168, in <module>
    fire.Fire(local_chat)
  File "/home/wangks/.conda/envs/ktransformers/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/.conda/envs/ktransformers/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/.conda/envs/ktransformers/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/ktransformers/ktransformers/local_chat.py", line 162, in local_chat
    generated = prefill_and_generate(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/ktransformers/ktransformers/util/utils.py", line 239, in prefill_and_generate
    next_token = torch.multinomial(probs, num_samples=1).squeeze(1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

检查了一下，发现输入的embedding是对的，经过model后的logits全部是nan。

**Comment by tunantu** [comment]
更新，进一步打印出每一层的推理过程，发现，模型在推理到第9层的时候出现错误：
8
tensor([[[-0.7148, -0.2969, -0.4551,  ..., -0.9688, -0.9922, -0.6250],
         [-0.0742, -0.0176,  0.0452,  ...,  0.0342,  0.0278,  0.0077],
         [ 0.0518, -0.1172, -0.0513,  ...,  0.0933, -0.0493, -0.0571],
         ...,
         [ 0.0024, -0.0349, -0.0144,  ...,  0.0068,  0.0645,  0.0298],
         [ 0.0342, -0.0378,  0.0723,  ...,  0.0483,  0.0894, -0.0037],
         [-0.0972, -0.0723,  0.0154,  ..., -0.0371,  0.0148,  0.0422]]],
       device='cuda:0')
9
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0')

可以看到，第8层仍旧可以成功推理出hidden state, 可是到第9层出现错误，开始变成nan。请教这个是什么问题呢？

**Comment by tunantu** [comment]
同样的环境，部署DeepSeek-V2-Lite-Chat不会出错。 并且按照FQA中的文档进行了检查，发现，我的g++是符合版本要求的。

**Comment by tunantu** [comment]
部署DeepSeek-R1-Q8_0也会报同样的错误

**Comment by Atream** [comment]
请更新最新版本的代码并重新编译，为确保重新编译生效，建议先删除旧版本的编译结果。如果仍然有nan的问题，请提供prompt

**Comment by Atream** [comment]
ubuntu内核是否使用的是20.04？我们观察到有时20.04会出现这个问题，22.04则不会

**Comment by tunantu** [comment]
> ubuntu内核是否使用的是20.04？我们观察到有时20.04会出现这个问题，22.04则不会

ubuntu是22.04. 已根据最新的代码重现实现了编译。还是这个问题。

Chat: Who are you
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wangks/ktransformers/ktransformers/local_chat.py", line 185, in <module>
    fire.Fire(local_chat)
  File "/home/wangks/.local/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/.local/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/.local/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/ktransformers/ktransformers/local_chat.py", line 179, in local_chat
    generated = prefill_and_generate(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangks/ktransformers/ktransformers/util/utils.py", line 214, in prefill_and_generate
    next_token = torch.multinomial(probs, num_samples=1).squeeze(1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

/pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.

**Comment by tunantu** [comment]
同时，能够跑起来DeepSeek-V2-Lite-Chat。 在部署R1的时候，我观测了显存和 内存的消耗，并未出现显存/内存不够用的情况。。

**Comment by tunantu** [comment]
问题已经解决。

原因： 下载到本地的GGUF文件和huggingface上官方版本的文件相比，文件遭到了损害。

解决思路：通过sha256sum计算下载下来的每个gguf文件的sha56值，和官方文件公布的sha256值进行对比，定位出受损害的文件。

解决方法:  定位出受损害的文件后，重新下载该文件即可。
